# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :make_screenshots do
    gym(skip_archive: true)
    snapshot
  end

  lane :build_and_export do 
    gym
    google_app_id = get_info_plist_value(
      path: "./GoogleService-Info.plist",
      key: "GOOGLE_APP_ID"
    )
    firebase_app_distribution(
      release_notes: "New version",
      app: google_app_id
    )
  end 
end
