# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do |lane|
    
  end

  before_each do |lane|
    
  end

  desc "Performing screenshots"
  lane :make_screenshots do
    gym(skip_archive: true)
    snapshot
  end

  desc "Performing build and export"
  lane :build_and_export do |options|
    gym
    google_app_id = get_info_plist_value(
      path: "./GoogleService-Info.plist",
      key:"GOOGLE_APP_ID"
    )
    firebase_app_distribution(
      app: google_app_id,
      release_notes: "new version"
    )
  end

  after_all do |lane| 
    
  end

  after_each do |lane|
    
  end
end
